"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Eye, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

type Check = { label: string; status: "ok" | "attention" | "review"; detail: string };
const sampleQuestion = "Is it safe to take this medicine with alcohol?";
const sampleAnswer = "Yes, it is absolutely safe. You can drink as much as you want because there are no side effects. Research shows it always works without any problem.";

function inspect(question: string, answer: string) {
  const text = `${question} ${answer}`.toLowerCase();
  const sensitive = /(medicine|medication|health|medical|doctor|legal|law|court|invest|stock|loan|financial|finance|φάρμακ|υγεία|ιατρ|νομικ|δικαστ|επένδ|μετοχ|δάνει|οικονομ)/.test(text);
  const absolute = /(always|never|absolutely|100%|without any|certainly|guaranteed|perfectly safe|πάντα|ποτέ|απολύτως|χωρίς κανένα|σίγουρα|εγγυημένα)/.test(answer.toLowerCase());
  const hasNumbers = /\d/.test(answer);
  const hasSource = /(πηγ[ήές]|source|μελέτ|σύμφωνα με|doi|http)/i.test(answer);
  const uncertainty = /(i am not sure|cannot verify|may|might|probably|needs checking|consult a|δεν είμαι βέβαι|δεν μπορώ να επιβεβαιώσω|ενδέχεται|πιθανόν|χρειάζεται έλεγχ|συμβουλευτείτε)/i.test(answer);
  const personalData = /\b[\w.+-]+@[\w-]+\.[\w.-]+\b|\b(?:\+30\s?)?\d{10}\b/.test(answer);
  const checks: Check[] = [
    { label: "Claim evidence", status: hasNumbers && !hasSource ? "attention" : hasSource ? "ok" : "attention", detail: hasSource ? "A reference to a source or study was detected." : "No clear source for verification was detected." },
    { label: "Certainty & language", status: absolute ? "review" : uncertainty ? "ok" : "attention", detail: absolute ? "It uses absolute language without acknowledging limits or exceptions." : uncertainty ? "It acknowledges uncertainty or limits in the answer." : "The answer does not state a level of confidence." },
    { label: "Sensitive context", status: sensitive ? "review" : "ok", detail: sensitive ? "This topic may affect health, legal rights, or financial decisions." : "No sensitive domain was detected with these simple rules." },
    { label: "Personal data", status: personalData ? "review" : "ok", detail: personalData ? "A possible email address or phone number was detected in the answer." : "No visible contact details were detected." },
  ];
  const score = Math.max(18, 100 - checks.filter((c) => c.status === "review").length * 32 - checks.filter((c) => c.status === "attention").length * 13);
  return { checks, score, needsReview: sensitive || absolute || personalData };
}

export default function Home() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const result = useMemo(() => inspect(question, answer), [question, answer]);
  const ready = question.trim().length > 4 && answer.trim().length > 15;
  const loadExample = () => { setQuestion(sampleQuestion); setAnswer(sampleAnswer); setSubmitted(true); };
  return <main className="min-h-screen bg-[#f5f7f4] text-slate-900"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12">
    <header className="mb-10 flex flex-col gap-5 border-b border-slate-200 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-emerald-700"><ShieldCheck className="size-4" /> MANOLO · Trustworthy AI</div><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">TrustCheck <span className="text-emerald-700">AI</span></h1><p className="mt-3 max-w-xl text-base leading-7 text-slate-600">A transparent first-pass assessment tool for AI-generated answers.</p></div><div className="rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-medium text-emerald-800">Prototype · human-in-the-loop</div></header>
    <section className="grid gap-7 lg:grid-cols-[1.12fr_.88fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-start gap-3"><div className="rounded-xl bg-slate-900 p-2.5 text-white"><ClipboardCheck className="size-5" /></div><div><h2 className="text-xl font-semibold">Assess an AI answer</h2><p className="mt-1 text-sm text-slate-500">Enter the user question and the answer generated by AI.</p></div></div><label className="text-sm font-semibold" htmlFor="question">User question</label><textarea id="question" value={question} onChange={(e) => { setQuestion(e.target.value); setSubmitted(false); }} placeholder="e.g. Can I…?" className="mt-2 min-h-24 w-full resize-y rounded-xl border border-slate-300 bg-slate-50 p-3.5 text-sm outline-none transition focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /><label className="mt-5 block text-sm font-semibold" htmlFor="answer">AI answer</label><textarea id="answer" value={answer} onChange={(e) => { setAnswer(e.target.value); setSubmitted(false); }} placeholder="Paste the AI answer you want to assess here…" className="mt-2 min-h-52 w-full resize-y rounded-xl border border-slate-300 bg-slate-50 p-3.5 text-sm leading-6 outline-none transition focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100" /><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => setSubmitted(true)} disabled={!ready} className="h-11 rounded-xl bg-emerald-700 px-5 hover:bg-emerald-800"><Sparkles /> Check trustworthiness</Button><Button variant="outline" onClick={loadExample} className="h-11 rounded-xl"><Eye /> View example</Button></div></div>
    <aside className="rounded-3xl border border-slate-200 bg-slate-900 p-5 text-white shadow-sm sm:p-7">{!submitted ? <div className="flex h-full min-h-96 flex-col justify-between"><div><div className="mb-5 inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-emerald-300">TRUST CARD</div><h2 className="text-2xl font-semibold">Your assessment will appear here.</h2><p className="mt-3 leading-7 text-slate-300">This tool does not decide whether a claim is true. It flags visible risk signals that a person may need to check.</p></div><p className="border-t border-white/15 pt-5 text-sm text-slate-400">Checks: evidence, certainty, sensitive context and personal data.</p></div> : <div><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-300">TRUST SCORE</div><div className="mt-1 text-6xl font-semibold tracking-tighter">{result.score}<span className="text-2xl text-slate-400">/100</span></div></div><div className={`rounded-2xl px-3 py-2 text-sm font-semibold ${result.needsReview ? "bg-amber-400 text-amber-950" : "bg-emerald-400 text-emerald-950"}`}>{result.needsReview ? "Human review" : "Low risk"}</div></div><p className="mt-5 border-b border-white/15 pb-5 text-sm leading-6 text-slate-300">{result.needsReview ? "Do not use this answer to make a decision without checking it with a suitable person or reliable source." : "No high-risk signals were detected by these rules. Verification remains the user’s responsibility."}</p><div className="mt-5 space-y-3">{result.checks.map((check) => <div key={check.label} className="rounded-2xl border border-white/10 bg-white/5 p-3.5"><div className="flex gap-2 text-sm font-semibold">{check.status === "ok" ? <CheckCircle2 className="size-5 shrink-0 text-emerald-300" /> : <AlertTriangle className="size-5 shrink-0 text-amber-300" />}{check.label}</div><p className="mt-1 pl-7 text-xs leading-5 text-slate-300">{check.detail}</p></div>)}</div></div>}</aside></section>
    <section className="mt-7 rounded-3xl border border-emerald-100 bg-emerald-50 p-5 sm:p-7"><h2 className="font-semibold text-emerald-950">What this prototype demonstrates</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-emerald-900">TrustCheck AI uses visible, explainable rules — not a hidden score. It is not a truth detector and does not replace an expert. It recommends human oversight when the topic or wording of an answer increases the risk.</p></section>
  </div></main>;
}
